dev: update bytes_to_felt_vec
sayajin-labs/kakarot-rpc pull request #128
Opened 2023-03-03 20:14 UTC by dpinones

Add unit testing for the function vec_felt_to_bytes in the helpers.rs file

Time spent on this PR: 0.5 day

Closes #NUMBER_OF_ISSUE

# Pull Request type #84 

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: N/A

# What is the new behavior?

-
-
-

# Does this introduce a breaking change?

- [ ] Yes
- [ ] No

# Other information

2023-03-03 20:36 UTC, dpinones commented
Danilo [commented](https://github.com/sayajin-labs/kakarot-rpc/issues/84#issuecomment-1453056904)  that the [`vec_felt_to_bytes`](https://github.com/sayajin-labs/kakarot-rpc/blob/ab59ebfb3878b6606e293f7ce42150727cc973bb/core/src/helpers.rs#L210) and [`bytes_to_felt_vec` ](https://github.com/sayajin-labs/kakarot-rpc/blob/ab59ebfb3878b6606e293f7ce42150727cc973bb/core/src/helpers.rs#L262) methods were inverse to each other. However, after running a test, it was found that they were not.

```
#[test]
fn test_bytes_to_felt_vec_and_vec_felt_to_bytes() {
    let input = Bytes::from(vec![
        1
    ]);

    let expected_output = vec![
        FieldElement::from(1_u64),
    ];
    assert_eq!(bytes_to_felt_vec(input.clone()), expected_output);
    assert_eq!(vec_felt_to_bytes(expected_output), input);
}
```

Analyzing the code, it was concluded that the `vec_felt_to_bytes` method was working correctly, but the `bytes_to_felt_vec` method had a problem. Instead of reading blocks of 32 bytes, it was reading blocks of 8 bytes.

I propose to correct the `bytes_to_felt_vec` method as follows(in the comment below)

If my analysis is correct, it is necessary to update all calls to the `bytes_to_felt_vec` method and add more test cases for both methods.
Please let me know if there are any corrections that need to be made. Thanks :)

2023-03-07 16:22 UTC, Eikix commented on core/src/helpers.rs
> +    let bytes_vec = bytes.to_vec();
why are we doing this refactor?
here, our goal is doing 1 byte = 1 felt 
Bytes -> Vec<u8> -> Vec<FieldElement>

2023-03-07 16:23 UTC, Eikix commented on core/src/helpers.rs
> +        let expected_output = vec![FieldElement::from(1_u64)];
here we'd want to do Bytes(0,0,0,0,0,...,1) -> vec![0,0,0,0...,1] -> vec![felt!(0), felt!(0), ..., felt!(1)]

2023-03-07 16:23 UTC, Eikix requested changes
nice PR! I think there was a misunderstanding in what we expected the function to accomplish

2023-03-16 16:36 UTC, Eikix commented on core/src/helpers.rs
> +    let bytes_vec = bytes.to_vec();
Yes, but here, since we are dealing with bytes, we know the value will be between 0 and 255 (since bytes.to_vec() will yield a Vec<u8>)

2023-03-16 16:43 UTC, Eikix commented
I think there was a misunderstanding on this PR / issue. I apologize for this.

Maybe we spoke too fast when we said both of these functions inverted each other, or our language was not precise enough.


In my view, @danilowhk can confirm, but `vec_felt_to_bytes` represents a vector of field elements that are between 0 and 255. In this util function, there should be some kind of check such that we know the Vec<FieldElement> is in fact a Vec<u8>.

Our sole purpose is to switch between types, but the underlying data will always be bytes, i.e. single values between 0 and 255. 

`vec_felt_to_bytes`'s flow:  Vec<FieldElement> -> Vec<u8> -> Bytes (granted each individual FieldElement is <2**8)
'bytes_to_vec_felt`'s flow: Bytes -> Vec<u8> -> Vec<FieldElement>

2023-04-14 09:31 UTC, closed without merging