Feat/getStorageAt
sayajin-labs/kakarot-rpc pull request #70
Opened 2023-02-05 14:11 UTC by trangnv

Time spent on this PR: 5h

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: N/A

# What is the new behavior?

- implementing `eth_getStorageAt`
-
-

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

2023-02-08 10:04 UTC, Eikix commented on core/src/lightclient/mod.rs
> +        let f = FieldElement::from_bytes_be(&bytes).unwrap();
Let's switch from using `.unwrap()` to handling if `from_bytes_be` fails, you will find other examples in the codebase where we handle from_bytes or other FieldElement methods that return a result/option using various methods (ok_or, unwrap_or_else, etc.)

2023-02-08 10:07 UTC, Eikix commented on rpc/src/eth_rpc.rs
> +    ) -> Result<Bytes> {
Nice catch! It seems reth's types are wrong. 
https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-api/src/eth.rs#L115

You can open an issue on their repo if you'd like to signal they're not respecting the ethereum json-rpc API https://ethereum.github.io/execution-apis/api-documentation/

2023-02-08 10:07 UTC, Eikix commented on rpc/src/eth_rpc.rs
> +        let starknet_block_id = ethers_block_id_to_starknet_block_id(_block_number.unwrap())?;
Let's not unwrap here but rather handle the error

2023-02-08 10:07 UTC, Eikix commented on rpc/src/eth_rpc.rs
> +        todo!()
You should rebase on main:)!

2023-02-08 10:08 UTC, Eikix commented on core/src/lightclient/mod.rs
> +        let ethereum_address_felt = FieldElement::from_hex_be(&address_hex).map_err(|e| {
nice error handling! let's reproduce it and replace .unwrap with this structure

2023-02-11 18:38 UTC, Eikix requested changes
Nice PR! Needs some reasonable amount of work to get it to a mergeable state:)

2023-02-20 14:15 UTC, closed without merging

2023-02-21 13:58 UTC, trangnv commented
will reopen soon, been sick with covid recently

2023-02-21 15:13 UTC, Eikix commented
I'm sorry to hear that, I hope you get well soon and rest well!